### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [ecki/lockdep-maven-plugin#1]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/net/eckenfels/mavenplugins/lockdeps/ProjectScanner.java: Line number => 39: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by ecki** [comment]
Actually It should use the checksum which the Repo uses, however sha-1 is still the format provided by most repo (browsers). But yes it should probably store both, common and secure variants.
